name: Update Figshare Item

on:
  push:
    branches:
      - SDIT_test_ambs  # Adjust this to your default branch

jobs:
  update-figshare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Update Figshare item
        env:
          FIGSHARE_API_TOKEN: ${{ secrets.FIGSHARE_API_TOKEN }}
        run: |
          python update_figshare.py
